name: Deploy Ghost to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Ghost-CLI
        run: npm install -g ghost-cli

      - name: Install dependencies
        run: npm install

      - name: Setup Ghost
        run: ghost install local

      - name: Build static files
        run: ghost build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./content
